-- Project Baca — development catalog seed (dev only, never production).
--
-- Four short original works under CC0 so the local catalog reads like a
-- library instead of test debris. Fixed ids make the seed idempotent and let
-- the web test suite pin a book (`crates/web/tests/conftest.py`). Covers are
-- empty on purpose: the typographic plate renders them.
--
-- Usage: make seed-dev

BEGIN;

INSERT INTO books (id, title, author, language, primary_theme, sub_theme, description, cover_url,
                   epub_storage_path, total_words, estimated_reading_minutes, source_name, source_url,
                   license, publication_year, status)
VALUES
  ('a0000000-0000-4000-8000-000000000001', 'Surat dari Pelabuhan Teluk', 'N. Larasati', 'id', 'Romansa', 'Surat-menyurat',
   'Dua sahabat masa kecil dipisahkan laut dan menyambung hidup lewat surat yang datang sebulan sekali. Sebuah kisah tentang kesetiaan kata-kata.',
   '', 'seed/surat-dari-pelabuhan-teluk.epub', 3600, 16, 'Pustaka Rotaria', NULL, 'CC0-1.0', 1931, 'published'),
  ('a0000000-0000-4000-8000-000000000002', 'Peta yang Tidak Pernah Selesai', 'Hadi Wiraatmadja', 'id', 'Petualangan', 'Ekspedisi',
   'Seorang juru gambar ikut ekspedisi menyusuri sungai pedalaman untuk menyelesaikan peta yang ditinggalkan ayahnya setengah jadi.',
   '', 'seed/peta-yang-tidak-pernah-selesai.epub', 3600, 16, 'Pustaka Rotaria', NULL, 'CC0-1.0', 1927, 'published'),
  ('a0000000-0000-4000-8000-000000000003', 'Lampu di Rumah Juru Tulis', 'Teguh Prasojo', 'id', 'Misteri', 'Kota kecil',
   'Setiap malam lampu di rumah juru tulis menyala sampai subuh, padahal pemiliknya sudah lama pergi. Warga mulai bertanya siapa yang menulis.',
   '', 'seed/lampu-di-rumah-juru-tulis.epub', 3600, 16, 'Pustaka Rotaria', NULL, 'CC0-1.0', 1935, 'published'),
  ('a0000000-0000-4000-8000-000000000004', 'The Quiet Ledger', 'Eleanor Whitcombe', 'en', 'Memoir', 'Working life',
   'A bookkeeper in a harbour town records a year of small accounts and discovers that the sums she keeps are not the ones that matter.',
   '', 'seed/the-quiet-ledger.epub', 3600, 16, 'Pustaka Rotaria', NULL, 'CC0-1.0', 1912, 'published')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title, author = EXCLUDED.author, language = EXCLUDED.language,
  primary_theme = EXCLUDED.primary_theme, sub_theme = EXCLUDED.sub_theme, description = EXCLUDED.description,
  cover_url = EXCLUDED.cover_url, total_words = EXCLUDED.total_words,
  estimated_reading_minutes = EXCLUDED.estimated_reading_minutes, source_name = EXCLUDED.source_name,
  license = EXCLUDED.license, publication_year = EXCLUDED.publication_year, status = EXCLUDED.status,
  updated_at = NOW();

INSERT INTO chapters (id, book_id, chapter_number, title, word_count, html_content) VALUES
  ('b0000000-0000-4000-8000-000000000101', 'a0000000-0000-4000-8000-000000000001', 1, 'Surat Pertama', 1200,
   '<p>Pelabuhan Teluk bangun lebih pagi daripada penghuninya. Sebelum azan subuh selesai, perahu-perahu nelayan sudah menggesek dermaga kayu, dan bau garam masuk lewat celah jendela rumah Laras di ujung gang. Ia menulis surat pertamanya di meja dapur, ditemani secangkir kopi yang sudah lama dingin dan sebatang pensil yang ujungnya ia runcingkan dengan pisau dapur.</p><p>Kepada Rania, tulisnya, lalu berhenti lama. Dua bulan sejak kapal membawa sahabatnya ke seberang, dan belum satu kalimat pun yang terasa cukup. Ia takut menulis terlalu banyak dan tampak merengek; ia takut menulis terlalu sedikit dan tampak sudah lupa.</p><p>Akhirnya ia menulis tentang pasar. Tentang ikan kembung yang harganya naik, tentang penjual kain yang kini membawa cucunya, tentang hujan yang turun tepat ketika ia menjemur seprai. Hal-hal kecil, pikirnya, adalah tali paling kuat untuk menyeberangi laut.</p><p>Ketika amplop itu ia serahkan ke kantor pos, petugasnya menimbangnya dengan telapak tangan dan tersenyum. Berat juga, katanya. Laras mengangguk. Ia tidak tahu bahwa surat itu akan dibaca lima kali sebelum dibalas, dan bahwa balasannya akan mengubah arah tahun-tahun berikutnya.</p>'),
  ('b0000000-0000-4000-8000-000000000102', 'a0000000-0000-4000-8000-000000000001', 2, 'Balasan dari Seberang', 1200,
   '<p>Balasan datang pada hari Kamis, dalam amplop cokelat yang sudutnya penyok. Rania menulis dengan tinta biru dan tangan yang tergesa, seolah kalimat-kalimatnya berlari mendahului pikirannya. Kota di seberang, katanya, berisik dengan cara yang berbeda: bukan ombak, melainkan roda dan bel sepeda dan orang-orang yang berbicara tanpa menatap.</p><p>Ia bekerja di sebuah percetakan kecil, menyusun huruf timah satu demi satu. Setiap malam jemarinya hitam dan punggungnya pegal, tetapi ia menyukai bunyi mesin yang berdentum seperti jantung besar. Di sela cerita itu, Rania menyelipkan satu kalimat yang tidak dijelaskan: ada seseorang yang mengantarnya pulang setiap Jumat.</p><p>Laras membaca kalimat itu berulang-ulang. Ia merasa senang, lalu merasa sesuatu yang lain, yang tidak punya nama. Ia menaruh surat itu di bawah bantal, sebuah kebiasaan dari masa kanak-kanak yang ia kira sudah ditinggalkan.</p><p>Esoknya ia membalas dengan cerita tentang perahu baru milik Pak Sanusi dan tentang anjing pelabuhan yang melahirkan empat anak. Ia tidak bertanya tentang hari Jumat. Beberapa pertanyaan, pikirnya, lebih baik dibiarkan menyeberang sendiri.</p>'),
  ('b0000000-0000-4000-8000-000000000103', 'a0000000-0000-4000-8000-000000000001', 3, 'Musim Hujan', 1200,
   '<p>Musim hujan membuat surat-surat datang terlambat dan basah di pinggirnya. Laras belajar mengeringkannya di atas tungku, membalik halaman demi halaman sampai tintanya berhenti merembes. Ada kata-kata yang hilang dengan cara itu, dan ia mengisi lubang-lubangnya dengan tebakan.</p><p>Pada surat kesebelas, Rania bercerita bahwa percetakan akan tutup. Pemiliknya sakit, mesin-mesin akan dijual, dan ia belum tahu ke mana kakinya akan melangkah. Orang yang mengantarnya pulang setiap Jumat, tulisnya, menawarkan sesuatu yang besar dan menakutkan. Ia meminta pendapat Laras, dan Laras tahu bahwa untuk pertama kalinya jawabannya akan benar-benar berarti.</p><p>Ia menulis sepanjang malam. Ia merobek tiga lembar, membakar dua, dan menyimpan satu. Ia menulis bahwa pelabuhan selalu punya satu dermaga kosong, bahwa rumah di ujung gang punya satu kamar yang tidak pernah dipakai, dan bahwa ia tidak akan pernah menyuruh siapa pun pulang jika pulang bukan yang diinginkan.</p><p>Surat itu ia kirim pagi-pagi. Petugas pos tidak menimbangnya kali ini; ia hanya mengangguk, seolah tahu bahwa beberapa surat tidak diukur dengan gram. Hujan turun lagi ketika Laras berjalan pulang, dan untuk pertama kalinya sejak kapal itu berangkat, ia tidak terburu-buru.</p>'),
  ('b0000000-0000-4000-8000-000000000201', 'a0000000-0000-4000-8000-000000000002', 1, 'Lembar yang Tertinggal', 1200,
   '<p>Peta itu berhenti di sebuah tikungan sungai, tepat di tempat pensil ayahnya patah dua puluh tahun lalu. Darma menemukannya dalam kotak kayu bersama kompas yang jarumnya sudah malas, dan pada malam itu juga ia memutuskan bahwa garis yang terputus harus ada yang menyambung.</p><p>Ekspedisi berangkat dari dermaga kecil dengan dua perahu panjang dan enam orang. Darma dibawa karena ia bisa menggambar, bukan karena ia bisa mendayung, dan hal itu dibuat jelas oleh Juru Mudi Sabar sejak hari pertama. Kau gambar, kami dayung, katanya, dan jangan pernah menukar keduanya.</p><p>Sungai di hulu berubah warna setiap jam. Pagi cokelat susu, siang hijau tembaga, sore seperti teh pekat yang dituang pelan. Darma mencatat semuanya di pinggir lembar peta, dengan huruf kecil-kecil yang hanya bisa ia baca sendiri.</p><p>Pada malam ketiga, ia membuka lembar ayahnya di bawah lentera dan menemukan satu kata yang ditulis terbalik di sudut: kembali. Ia tidak tahu apakah itu perintah, peringatan, atau sekadar catatan tentang arah arus. Ia melipatnya kembali dan tidak menceritakannya kepada siapa pun.</p>'),
  ('b0000000-0000-4000-8000-000000000202', 'a0000000-0000-4000-8000-000000000002', 2, 'Jeram Tujuh', 1200,
   '<p>Jeram Tujuh terdengar sebelum terlihat: deru rendah yang membuat air di dalam cangkir bergetar. Sabar menyuruh semua orang turun dan menarik perahu lewat tepian berbatu, dan selama dua hari mereka berjalan lebih banyak daripada berlayar.</p><p>Darma menggambar jeram itu dari atas tebing, dengan kaki menggantung dan jantung yang berdegup lebih keras daripada yang ingin ia akui. Tujuh undakan air, tujuh garis putih yang berkelok, dan di antaranya batu-batu hitam yang tampak seperti punggung binatang tidur.</p><p>Ketika ia turun, Sabar memeriksa gambarnya lama sekali. Kau menggambar arusnya, katanya akhirnya, bukan hanya batunya. Ayahmu dulu hanya menggambar batu. Itu pujian pertama yang Darma terima, dan ia menyimpannya seperti orang menyimpan uang logam langka.</p><p>Malam itu salah satu perahu bocor. Mereka menambalnya dengan getah dan kain sarung, dan Darma menyadari bahwa peta yang bagus tidak pernah menolong orang yang perahunya tenggelam. Ia mulai menggambar lebih cepat.</p>'),
  ('b0000000-0000-4000-8000-000000000203', 'a0000000-0000-4000-8000-000000000002', 3, 'Garis Terakhir', 1200,
   '<p>Hulu sungai ternyata bukan mata air, melainkan danau yang tenang dan sangat luas, dikelilingi hutan yang tidak pernah mendengar nama siapa pun. Perahu-perahu berhenti di tepinya seperti dua kalimat yang kehabisan kata.</p><p>Darma membentangkan lembar ayahnya di atas lembarnya sendiri. Garis yang terputus di tikungan itu kini punya kelanjutan: jeram, tebing, danau, dan satu titik kecil tempat mereka berdiri. Ia menyambungnya dengan satu tarikan pensil, dan tangannya tidak gemetar.</p><p>Sabar bertanya apakah ia akan menulis namanya di peta itu. Darma berpikir sebentar, lalu menulis dua nama berdampingan, dan di bawahnya nama enam orang yang mendayung. Peta, katanya, bukan milik yang menggambar.</p><p>Dalam perjalanan pulang, arus membawa mereka lebih cepat daripada yang mereka inginkan, dan Darma akhirnya mengerti kata yang ditulis terbalik di sudut lembar ayahnya. Kembali, bukan berhenti. Ia menggambar sampai lentera habis.</p>'),
  ('b0000000-0000-4000-8000-000000000301', 'a0000000-0000-4000-8000-000000000003', 1, 'Lampu yang Tidak Padam', 1200,
   '<p>Rumah juru tulis di ujung jalan kecamatan sudah kosong tiga tahun, sejak pemiliknya pindah ke kota tanpa pamit. Namun setiap malam, lewat pukul sembilan, jendela ruang depannya menyala kuning hangat, dan bayangan seseorang yang membungkuk di atas meja bergerak pelan di tirainya.</p><p>Warga punya penjelasan masing-masing. Pak Lurah bilang itu pantulan lampu jalan. Bu Marni yang menjual nasi di seberang bilang itu arwah yang belum selesai menagih utang. Anak-anak bilang itu hantu yang sedang mengerjakan PR, dan mereka tertawa, tetapi tidak ada yang berani lewat sendirian.</p><p>Hanya Sekar, guru sekolah dasar yang baru pindah, yang berdiri cukup lama di depan rumah itu untuk menyadari sesuatu: bayangan itu menulis dengan tangan kiri, dan setiap beberapa menit berhenti untuk mencelupkan pena. Pena, pikirnya. Siapa yang masih memakai pena celup?</p><p>Ia pulang dengan rasa penasaran yang tidak enak dan bermanfaat sekaligus, seperti gigi yang goyang. Malam itu ia menulis di buku hariannya: lampu menyala 21.10, padam 04.30, bayangan kidal. Ia belum tahu bahwa catatan kecil itu akan menjadi halaman pertama dari sesuatu yang lebih panjang.</p>'),
  ('b0000000-0000-4000-8000-000000000302', 'a0000000-0000-4000-8000-000000000003', 2, 'Tinta Hijau', 1200,
   '<p>Surat pertama muncul di kotak pos sekolah pada hari Senin, tanpa perangko dan tanpa nama pengirim. Isinya satu halaman tulisan tangan dengan tinta hijau: sebuah daftar nama murid yang tidak datang hari itu, lengkap dengan alasannya. Semuanya benar.</p><p>Sekar membawanya ke kantor camat, dan kantor camat mengembalikannya dengan senyum sopan yang berarti silakan urus sendiri. Maka ia mengurusnya sendiri. Ia membandingkan tulisan itu dengan arsip lama di kelurahan dan menemukan catatan kelahiran, catatan tanah, catatan nikah, semuanya dengan tangan yang sama dan tinta yang sama.</p><p>Juru tulis itu bernama Harja, dan menurut arsip ia berusia tujuh puluh satu tahun ketika pergi. Tidak ada catatan kematian. Tidak ada catatan kepindahan. Hanya satu baris di buku tamu kelurahan: berpamitan sementara, 3 Maret.</p><p>Malam itu Sekar duduk di beranda Bu Marni dengan sepiring pisang goreng dan menatap jendela kuning di seberang. Bayangan itu menulis seperti biasa. Kali ini ia menghitung: dua puluh tiga kali mencelup pena dalam satu jam. Orang yang rajin, pikirnya. Atau orang yang punya banyak sekali yang harus diselesaikan.</p>'),
  ('b0000000-0000-4000-8000-000000000303', 'a0000000-0000-4000-8000-000000000003', 3, 'Halaman yang Belum Ditulis', 1200,
   '<p>Pintu rumah itu tidak dikunci. Sekar mengetahuinya pada malam ketujuh, ketika hujan memaksanya berteduh di beranda dan daun pintu bergeser sendiri karena angin. Di dalam, lampu minyak menyala di atas meja, pena celup berdiri di botol tinta hijau, dan tidak ada siapa-siapa.</p><p>Di atas meja tersusun buku-buku besar bersampul kain, masing-masing bertuliskan satu tahun. Ia membuka yang paling atas dan menemukan tahun ini, ditulis sampai tanggal hari itu. Nama-nama warga, kelahiran, kematian, siapa yang menikah, siapa yang berutang, siapa yang pindah. Halaman berikutnya kosong, menunggu.</p><p>Di laci ia menemukan sepucuk surat yang ditujukan kepada siapa pun yang datang. Harja menulis bahwa sebuah kampung yang berhenti dicatat akan berhenti mengingat dirinya sendiri, dan bahwa ia sudah terlalu tua untuk menyalakan lampu setiap malam. Ia meminta orang yang membaca surat itu untuk melanjutkan satu halaman saja, lalu memutuskan sendiri.</p><p>Sekar duduk. Ia mencelupkan pena, menulis tanggal, dan menulis hal pertama yang ia tahu: hujan deras, sekolah libur, Bu Marni menjual pisang goreng tiga puluh buah. Di luar, seorang anak yang lewat melihat bayangan di tirai bergerak dan berlari pulang untuk bercerita bahwa hantu juru tulis ternyata tidak kidal lagi.</p>'),
  ('b0000000-0000-4000-8000-000000000401', 'a0000000-0000-4000-8000-000000000004', 1, 'January', 1200,
   '<p>The ledger arrived before I did. It sat on the desk of the harbour office with its spine already cracked, and the clerk who was leaving tapped it twice, as one taps a horse one is handing over, and said that the columns would tell me everything I needed to know. He was wrong about that, as he was wrong about the weather, but I did not know it yet.</p><p>January in a harbour town is a month of small accounts. Rope mended, lamps refilled, a crate of oranges lost to frost and written off at cost. I learned the handwriting of the fishermen before I learned their faces, and I learned to read the tide tables before I learned the way home in the dark.</p><p>The widow Pell came on the ninth to settle a debt that was not hers. Her husband had owed for a net, and she paid it in coins so worn that the king on them had lost his nose. I entered the sum and did not enter the look on her face, and that was the first time I understood what a ledger leaves out.</p><p>At night the office smelled of ink and tar. I kept the book open under the lamp longer than the work required, reading the old entries as if they were letters. Somebody had kept these pages for forty years. Somebody had cared about a crate of oranges.</p>'),
  ('b0000000-0000-4000-8000-000000000402', 'a0000000-0000-4000-8000-000000000004', 2, 'The Spring Tides', 1200,
   '<p>By April the harbour master trusted me with the keys, which meant he trusted me with the mornings. I opened the office at six, lit the stove, and watched the spring tides climb the quay steps one stone at a time. The fishermen said the sea was counting too, and that it was a worse bookkeeper than I was.</p><p>A boat went down off the point that month. Two men came back and one did not, and for a week the ledger had nothing to say about it, because a drowned man owes nothing and is owed nothing. Then the chandler brought in a bill for the lost gear, and I wrote the dead man''s name for the first time, in a column headed loss.</p><p>I began a second book that spring, a small one, bound in grey cloth, which I kept in the drawer with the stamps. In it I wrote what the big ledger could not hold: that the widow Pell had taken in the drowned man''s dog, that the chandler had torn up half his bill, that the surviving men did not go out for nine days and then went out together.</p><p>The harbour master found the grey book in June. He read a page, closed it, and said nothing for a long moment. Then he told me that his predecessor had kept one too, and that it had been buried with him, and that he had always thought this a waste.</p>'),
  ('b0000000-0000-4000-8000-000000000403', 'a0000000-0000-4000-8000-000000000004', 3, 'Closing the Year', 1200,
   '<p>December came in sideways, with rain that the lamps could not keep out. I closed the year on the last Friday, ruling the final line beneath the final sum and finding, as every bookkeeper finds, that the columns agreed with each other and with nothing else.</p><p>The harbour master retired at Christmas. He left me his chair, his tide tables, and a sentence I have kept longer than any of them: that the figures are true, but the town is truer. I did not understand him then. I think I am beginning to.</p><p>On New Year''s Eve I took both books down to the quay. I did not throw either into the water; I am a bookkeeper, not a poet. I only sat with them on the cold stone and listened to the sea doing its own accounts, and I decided which of the two I would show to whoever came after me.</p><p>The grey book is on the desk now, beside the ledger, where the clerk who comes next will find it first. I have written on its first page the only instruction I trust: enter what happened, then enter what it cost, and never mistake the second for the first.</p>')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title, word_count = EXCLUDED.word_count, html_content = EXCLUDED.html_content;

INSERT INTO tags (id, name, slug) VALUES
  ('c0000000-0000-4000-8000-000000000001', 'Surat-menyurat', 'rotaria-surat'),
  ('c0000000-0000-4000-8000-000000000002', 'Ekspedisi sungai', 'rotaria-ekspedisi'),
  ('c0000000-0000-4000-8000-000000000003', 'Kota kecil', 'rotaria-kota-kecil'),
  ('c0000000-0000-4000-8000-000000000004', 'Harbour life', 'rotaria-harbour')
ON CONFLICT DO NOTHING;

INSERT INTO book_tags (book_id, tag_id)
SELECT b.id, t.id FROM (VALUES
  ('a0000000-0000-4000-8000-000000000001'::uuid, 'rotaria-surat'),
  ('a0000000-0000-4000-8000-000000000002'::uuid, 'rotaria-ekspedisi'),
  ('a0000000-0000-4000-8000-000000000003'::uuid, 'rotaria-kota-kecil'),
  ('a0000000-0000-4000-8000-000000000004'::uuid, 'rotaria-harbour')) AS b(id, slug)
JOIN tags t ON t.slug = b.slug
ON CONFLICT DO NOTHING;

COMMIT;
